// Loading and error states
export const SET_FACILITIES_LOADING = 'SET_FACILITIES_LOADING';
export const SET_FACILITIES_ERROR = 'SET_FACILITIES_ERROR';

// Facility data management
export const SET_USER_FACILITIES = 'SET_USER_FACILITIES';
export const SET_SELECTED_FACILITY = 'SET_SELECTED_FACILITY';
export const CLEAR_FACILITIES_DATA = 'CLEAR_FACILITIES_DATA';

// Facility-specific data
export const SET_FACILITY_PATIENTS = 'SET_FACILITY_PATIENTS';
export const SET_FACILITY_SERVICES = 'SET_FACILITY_SERVICES';
export const SET_FACILITY_STAFF = 'SET_FACILITY_STAFF';
export const SET_FACILITY_APPOINTMENTS = 'SET_FACILITY_APPOINTMENTS';
export const SET_FACILITY_USERS = 'SET_FACILITY_USERS';

// Service management actions
export const ADD_FACILITY_SERVICE = 'ADD_FACILITY_SERVICE';
export const UPDATE_FACILITY_SERVICE = 'UPDATE_FACILITY_SERVICE';
export const REMOVE_FACILITY_SERVICE = 'REMOVE_FACILITY_SERVICE';

// Appointment management actions
export const ADD_FACILITY_APPOINTMENT = 'ADD_FACILITY_APPOINTMENT';
export const UPDATE_FACILITY_APPOINTMENT = 'UPDATE_FACILITY_APPOINTMENT';
export const REMOVE_FACILITY_APPOINTMENT = 'REMOVE_FACILITY_APPOINTMENT';
