name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy to AWS EKS
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # Checkout the source code
      - name: Checkout source
        uses: actions/checkout@v3

      # Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image to ECR
      - name: Build, tag, and push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
        run: |
          echo "🔧 Building Docker image..."
          REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
          IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          # Replace <IMAGE_URI> in deployment template without modifying original
          sed "s|<IMAGE_URI>|$IMAGE_URI|g" k8s/deployment.yaml > k8s/deployment.generated.yaml

      # Update kubeconfig to access your EKS cluster
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      # Deploy to EKS using kubectl
      - name: Apply Kubernetes manifests
        run: |
          echo "🚀 Deploying to EKS..."
          kubectl apply -f k8s/deployment.generated.yaml
          kubectl apply -f k8s/service.yaml
